<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_youtube"
 *
 * Auto generated by Extension Builder 2017-08-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Plugin for YouTube.com',
    'description' => 'One of the only TYPO3 extension which provides to integrate all the features of Youtube.com like Simple Video, Channel, Playlist and Live-stream to your TYPO3 site. Know more from extension manual.',
    'category' => 'plugin',
    'author' => 'Sanjay Chuahan [NITSAN Technologies]',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-9.3.3',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
